---
- name: install tomcat10
  become: yes
  host: appserver
  vars:
    username: tomcat
    groupname: tomcat
    homedir: /opt/tomcat
    shell: /bin/false
  tasks:
    - name: install -jdk
      ansible.builtin.apt:
        name: "opendk-{{ java_version }}-jdk"
        update_cache: yes
        state: present
    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: {{ groupname }}
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: {{ username }}
        group: {{ groupname }}
        home: {{ homedir }}
        create_home: true
        shell: {{ shell }}

