---
- name: install tomcat 10
  become: yes
  hosts: appservers
  vars:
    username: tomcat
    groupname: tomcat
    homedir: /opt/tomcat
    shell: /bin/false
    tomcat_major_version: 10
    tomcat_specific_version: 10.1.14
    download_url: 
  tasks:
    - name: install jdk
      ansible.builtin.apt:
        name: "openjdk-{{ java_version }}-jdk"
        update_cache: yes
        state: present
    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: "{{ groupname }}"
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ groupname }}"
        home: "{{ homedir }}"
        create_home: true
        shell: "{{ shell }}"
    - name: download tomcat
      ansible.builtin.get_url:
<<<<<<< HEAD
        url: "https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_specific_version }}/bin/apache-tomcat-{{ tomcat_specific_version }}.tar.gz"
=======
        url: "https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_specific_version  }}/bin/apache-tomcat-{{ tomcat_specific_version }}.tar.gz"
>>>>>>> 4f146024f8d5a944756885d40d3400645a825896
        dest: "/tmp//apache-tomcat-{{ tomcat_specific_version }}.tar.gz"
    - name: extract tomcat
      ansible.builtin.unarchive:
        copy: true
        create: "{{ homedir }}/apache-tomcat-{{ tomcat_specific_version }}"
        src: "/tmp//apache-tomcat-{{ tomcat_specific_version }}.tar.gz"
        dest: "{{ homedir }}"
        group: "{{ groupname }}"
        owner: "{{ username }}"
        remote_src: yes